setwd("C:/Users/kevin/Desktop/R Programming/Exploratory data analysis/exdata_data_household_power_consumption")
data<-read.csv2("household_power_consumption.txt")
data$Date<-as.Date(as.character(data$Date),"%d/%m/%Y")
data<-data[data$Date>as.Date("2007-01-31"),]
data<-data[data$Date<as.Date("2007-02-03"),]
data$dayformat<-with(data, as.POSIXct(paste(Date, Time)))
data$Global_active_power<-as.numeric(data$Global_active_power)
data$Global_reactive_power<-as.numeric(data$Global_reactive_power)
data$Voltage<-as.numeric(data$Voltage)
par(mfrow=c(2,2))
par(mar=c(5,4,4,1))
plot(data$dayformat,data$Global_active_power, type="l", ylab="Global_Active_Power",xlab=" ")
plot(data$dayformat,data$Voltage, type="l", ylab="Voltage",xlab="datetime")
plot(data$dayformat,data$Sub_metering_1, type="l",ylab="Energy sub metering", xlab=" ")
lines(data$dayformat,data$Sub_metering_2, type = "l", col = "red")
lines(data$dayformat,data$Sub_metering_3, type = "l", col = "blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,cex = 0.5)
plot(data$dayformat,data$Global_reactive_power, type="l", ylab="Global_reactive_power",xlab="datetime")
dev.copy(png, file="plot4.png")
dev.off()